name: Hullo Bot

on: 
    pull_request: 
        branches:
            - main
            - workflows

    push: 
        branches:
            - main
            - workflows

jobs: 
    say-hello:
		# Operating System
        runs-on: ubuntu-latest	
		# Steps
        steps:
            - name: Print a message
              run: echo "Hello, from Hullo-Bot"
